# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44669523317101bc1c69c46305005b0600c1e6722523fe484dbf3f25842b86704bf86434c54c05724f96c5a007255bbcaabf48871c5aee2c49ca28da4ae38081

test:
  secret_key_base: c18386ae8a01b93b1446956711eb45da966d03b00a8d88b324c198bef929c5bc39dac04b2670d301e4095c7e39898a4be481a26f12bc0e4d94810342e5e51e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
